<?php

declare(strict_types=1);

use Illuminate\Contracts\Events\ShouldDispatchAfterCommit;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Event;
use Storix\Actions\CreateDispatchAction;
use Storix\Data\CreateDispatchData;
use Storix\Events\GenerateDraftDispatchRequested;
use Storix\Listeners\GenerateDraftDispatch;
use Storix\Models\Container;
use Storix\Models\Dispatch;
use Storix\Models\DispatchEntry;
use Storix\Tests\Fixtures\Models\DeliveryNote;
use Storix\Tests\Fixtures\Models\User;

it('encapsulates an immutable draft generation request that dispatches after commit', function (): void {
    $data = new CreateDispatchData(
        deliveryNoteId: 10,
        dispatchedBy: 20,
        quantity: 2,
        customerId: 15,
        dispatchedAt: '2026-07-20 09:00:00',
        dispatchNote: 'Generated by a host workflow',
        containerIds: [30, 40],
        idempotencyKey: 'delivery-note:10:draft-dispatch',
        metadata: ['source' => 'delivery-note-approved'],
    );

    $event = new GenerateDraftDispatchRequested($data);

    expect($event)->toBeInstanceOf(ShouldDispatchAfterCommit::class)
        ->and($event->data)->toBe($data)
        ->and($event->data->deliveryNoteId)->toBe(10)
        ->and($event->data->quantity)->toBe(2)
        ->and($event->data->containerIds)->toBe([30, 40])
        ->and($event->data->metadata)->toBe(['source' => 'delivery-note-approved']);
});

it('registers the draft generation listener with the package event dispatcher', function (): void {
    Event::fake();

    Event::assertListening(
        GenerateDraftDispatchRequested::class,
        GenerateDraftDispatch::class,
    );
});

it('generates a draft dispatch with reservations and audit context', function (): void {
    $user = User::query()->create(['name' => 'Event Dispatcher', 'email' => 'event-dispatch@example.com']);
    $deliveryNote = DeliveryNote::query()->create(['name' => 'Event delivery']);
    $container = Container::factory()->create();

    GenerateDraftDispatchRequested::dispatch(new CreateDispatchData(
        deliveryNoteId: $deliveryNote->id,
        dispatchedBy: $user->id,
        quantity: 1,
        customerId: $deliveryNote->customer_id,
        dispatchedAt: '2026-07-20 09:30:00',
        dispatchNote: 'Created from delivery note approval',
        containerIds: [$container->id],
        idempotencyKey: 'delivery-note:event-delivery:draft-dispatch',
        metadata: [
            'source' => 'delivery-note-approved',
            'correlation_id' => 'correlation-1001',
        ],
    ));

    $dispatch = Dispatch::query()
        ->where('idempotency_key', 'delivery-note:event-delivery:draft-dispatch')
        ->firstOrFail();

    expect((string) $dispatch->state)->toBe('draft')
        ->and($dispatch->delivery_note_id)->toBe($deliveryNote->id)
        ->and($dispatch->dispatched_by)->toBe($user->id)
        ->and($dispatch->dispatched_at?->toDateTimeString())->toBe('2026-07-20 09:30:00')
        ->and($dispatch->dispatch_note)->toBe('Created from delivery note approval')
        ->and($dispatch->metadata)->toBe([
            'source' => 'delivery-note-approved',
            'correlation_id' => 'correlation-1001',
        ])
        ->and($dispatch->entries)->toHaveCount(1)
        ->and($dispatch->entries->first()?->container_id)->toBe($container->id)
        ->and(Container::query()->availableForDispatch()->pluck('id'))->not->toContain($container->id);
});

it('defers generation until the surrounding transaction commits', function (): void {
    $user = User::query()->create(['name' => 'Commit Dispatcher', 'email' => 'commit@example.com']);
    $deliveryNote = DeliveryNote::query()->create(['name' => 'Committed delivery']);
    $startingTransactionLevel = DB::transactionLevel();

    DB::beginTransaction();

    try {
        GenerateDraftDispatchRequested::dispatch(new CreateDispatchData(
            deliveryNoteId: $deliveryNote->id,
            dispatchedBy: $user->id,
            quantity: 1,
            customerId: $deliveryNote->customer_id,
            idempotencyKey: 'delivery-note:commit:draft-dispatch',
        ));

        expect(Dispatch::query()->where('idempotency_key', 'delivery-note:commit:draft-dispatch')->exists())
            ->toBeFalse();

        DB::commit();
    } finally {
        while (DB::transactionLevel() > $startingTransactionLevel) {
            DB::rollBack();
        }
    }

    expect(Dispatch::query()->where('idempotency_key', 'delivery-note:commit:draft-dispatch')->exists())
        ->toBeTrue();
});

it('discards generation when the surrounding transaction rolls back', function (): void {
    $user = User::query()->create(['name' => 'Rollback Dispatcher', 'email' => 'rollback@example.com']);
    $deliveryNote = DeliveryNote::query()->create(['name' => 'Rolled back delivery']);
    $startingTransactionLevel = DB::transactionLevel();

    DB::beginTransaction();

    try {
        GenerateDraftDispatchRequested::dispatch(new CreateDispatchData(
            deliveryNoteId: $deliveryNote->id,
            dispatchedBy: $user->id,
            quantity: 1,
            customerId: $deliveryNote->customer_id,
            idempotencyKey: 'delivery-note:rollback:draft-dispatch',
        ));

        expect(Dispatch::query()->where('idempotency_key', 'delivery-note:rollback:draft-dispatch')->exists())
            ->toBeFalse();

        DB::rollBack();
    } finally {
        while (DB::transactionLevel() > $startingTransactionLevel) {
            DB::rollBack();
        }
    }

    expect(Dispatch::query()->where('idempotency_key', 'delivery-note:rollback:draft-dispatch')->exists())
        ->toBeFalse();
});

it('handles equivalent retries without creating duplicate dispatches or reservations', function (): void {
    $user = User::query()->create(['name' => 'Retry Dispatcher', 'email' => 'retry@example.com']);
    $deliveryNote = DeliveryNote::query()->create(['name' => 'Retry delivery']);
    $firstContainer = Container::factory()->create();
    $secondContainer = Container::factory()->create();

    $firstRequest = new CreateDispatchData(
        deliveryNoteId: $deliveryNote->id,
        dispatchedBy: $user->id,
        quantity: 2,
        customerId: $deliveryNote->customer_id,
        dispatchedAt: '2026-07-20 10:00:00',
        dispatchNote: 'Retry-safe request',
        containerIds: [$secondContainer->id, $firstContainer->id],
        idempotencyKey: 'delivery-note:retry:draft-dispatch',
        metadata: [
            'source' => 'queued-job',
            'context' => ['sequence' => 10, 'tenant' => 'central'],
        ],
    );
    $equivalentRetry = new CreateDispatchData(
        deliveryNoteId: $deliveryNote->id,
        dispatchedBy: $user->id,
        quantity: 2,
        customerId: $deliveryNote->customer_id,
        dispatchedAt: '2026-07-20 10:00:00',
        dispatchNote: 'Retry-safe request',
        containerIds: [$firstContainer->id, $secondContainer->id],
        idempotencyKey: 'delivery-note:retry:draft-dispatch',
        metadata: [
            'context' => ['tenant' => 'central', 'sequence' => 10],
            'source' => 'queued-job',
        ],
    );

    GenerateDraftDispatchRequested::dispatch($firstRequest);
    GenerateDraftDispatchRequested::dispatch($equivalentRetry);

    $dispatch = Dispatch::query()
        ->where('idempotency_key', 'delivery-note:retry:draft-dispatch')
        ->firstOrFail();

    expect(Dispatch::query()->count())->toBe(1)
        ->and($dispatch->idempotency_fingerprint)->toMatch('/^[a-f0-9]{64}$/')
        ->and($dispatch->entries)->toHaveCount(2)
        ->and(DispatchEntry::query()->count())->toBe(2);
});

it('rejects conflicting reuse of an idempotency key', function (): void {
    $user = User::query()->create(['name' => 'Conflict Dispatcher', 'email' => 'conflict@example.com']);
    $deliveryNote = DeliveryNote::query()->create(['name' => 'Conflict delivery']);

    GenerateDraftDispatchRequested::dispatch(new CreateDispatchData(
        deliveryNoteId: $deliveryNote->id,
        dispatchedBy: $user->id,
        quantity: 1,
        customerId: $deliveryNote->customer_id,
        dispatchedAt: '2026-07-20 10:30:00',
        dispatchNote: 'Original request',
        idempotencyKey: 'delivery-note:conflict:draft-dispatch',
    ));

    expect(fn () => GenerateDraftDispatchRequested::dispatch(new CreateDispatchData(
        deliveryNoteId: $deliveryNote->id,
        dispatchedBy: $user->id,
        quantity: 1,
        customerId: $deliveryNote->customer_id,
        dispatchedAt: '2026-07-20 10:30:00',
        dispatchNote: 'Conflicting request',
        idempotencyKey: 'delivery-note:conflict:draft-dispatch',
    )))->toThrow(
        DomainException::class,
        'The dispatch idempotency key [delivery-note:conflict:draft-dispatch] has already been used for another request.',
    );

    expect(Dispatch::query()->count())->toBe(1);
});

it('treats a quantity change as conflicting idempotent input', function (): void {
    $user = User::query()->create(['name' => 'Quantity Dispatcher', 'email' => 'quantity-conflict@example.com']);
    $deliveryNote = DeliveryNote::query()->create(['name' => 'Quantity conflict delivery']);

    GenerateDraftDispatchRequested::dispatch(new CreateDispatchData(
        deliveryNoteId: $deliveryNote->id,
        dispatchedBy: $user->id,
        quantity: 4,
        customerId: $deliveryNote->customer_id,
        idempotencyKey: 'delivery-note:quantity-conflict:draft-dispatch',
    ));

    expect(fn () => GenerateDraftDispatchRequested::dispatch(new CreateDispatchData(
        deliveryNoteId: $deliveryNote->id,
        dispatchedBy: $user->id,
        quantity: 5,
        customerId: $deliveryNote->customer_id,
        idempotencyKey: 'delivery-note:quantity-conflict:draft-dispatch',
    )))->toThrow(
        DomainException::class,
        'The dispatch idempotency key [delivery-note:quantity-conflict:draft-dispatch] has already been used for another request.',
    );

    expect(Dispatch::query()->sole()->quantity)->toBe(4);
});

it('rolls back the complete draft when reservation validation fails', function (): void {
    $user = User::query()->create(['name' => 'Invalid Dispatcher', 'email' => 'invalid@example.com']);
    $deliveryNote = DeliveryNote::query()->create(['name' => 'Invalid delivery']);
    $container = Container::factory()->create(['is_active' => false]);

    expect(fn () => GenerateDraftDispatchRequested::dispatch(new CreateDispatchData(
        deliveryNoteId: $deliveryNote->id,
        dispatchedBy: $user->id,
        quantity: 1,
        customerId: $deliveryNote->customer_id,
        containerIds: [$container->id],
        idempotencyKey: 'delivery-note:invalid:draft-dispatch',
    )))->toThrow(DomainException::class, "Container [{$container->serial}] is inactive.");

    expect(Dispatch::withTrashed()->where('idempotency_key', 'delivery-note:invalid:draft-dispatch')->exists())
        ->toBeFalse()
        ->and(DispatchEntry::withTrashed()->exists())->toBeFalse();
});

it('preserves direct unkeyed action behavior', function (): void {
    $user = User::query()->create(['name' => 'Manual Dispatcher', 'email' => 'manual@example.com']);
    $deliveryNote = DeliveryNote::query()->create(['name' => 'Manual delivery']);
    $data = new CreateDispatchData(
        deliveryNoteId: $deliveryNote->id,
        dispatchedBy: $user->id,
        quantity: 1,
        customerId: $deliveryNote->customer_id,
        dispatchedAt: '2026-07-20 11:00:00',
    );

    app(CreateDispatchAction::class)->handle($data);
    app(CreateDispatchAction::class)->handle($data);

    expect(Dispatch::query()->count())->toBe(2)
        ->and(Dispatch::query()->whereNull('idempotency_key')->count())->toBe(2);
});
